Vagrant.configure("2") do |config|
  nodes = {
    "master1" => { :ip => "192.168.56.11", :cpus => 2, :memory => 4096 },
    "master2" => { :ip => "192.168.56.12", :cpus => 2, :memory => 4096 },
    "master3" => { :ip => "192.168.56.13", :cpus => 2, :memory => 4096 },
    "worker1" => { :ip => "192.168.56.21", :cpus => 2, :memory => 4096 },
    "worker2" => { :ip => "192.168.56.22", :cpus => 2, :memory => 4096 },
  }

  config.vm.box = "ubuntu/jammy64"

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: opts[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.cpus = opts[:cpus]
        vb.memory = opts[:memory]
      end
      node.vm.provision "shell", inline: "sudo apt update -y"
    end
  end
end
